name: CI with micromamba

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  schedule:
  - cron: "0 5 * * TUE"

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:

    - uses: actions/checkout@v3

    - name: Setup micromamba
      uses: mamba-org/setup-micromamba@v1
      with:
        micromamba-version: latest
        environment-file: environment_dev.yaml
        log-level: debug
        init-shell: bash
        # ensure up-to-date environment with clean PyPSA dev installation
        cache-environment: false
        cache-downloads: true

    - name: Print installed dependencies
      run: |
        micromamba list

    - name: Install remaining packages
      run: |
        pip install pypower "pandapower>=2.0"

    - name: Install PyPSA commit
      run: |
        pip install --no-cache-dir --no-deps -e .

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Test with pytest
      run: |
        pytest --cov=./ --cov-report=xml

    - name: Upload code coverage report
      if: matrix.os == 'ubuntu-latest'
      uses: codecov/codecov-action@v3
